### ISSUE TITLE
Module doesn't work with LG G2

### ISSUE THREAD

**Issue by Vasioky** [MohammadAG/NFCLockscreenoffEnabler#19]
error:
java.lang.NoSuchMethodError: com.android.nfc.LNfcService#onRemoteEndpointDiscovered(com.android.nfc.DeviceHost.TagEndpoint)#exact
    at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:179)
    at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:129)
    at pk.qwerty12.nfclockscreenoffenabler.NFCLockScreenOffEnabler.handleLoadPackage(NFCLockScreenOffEnabler.java:448)
    at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
    at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
    at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
    at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
    at android.app.ActivityThread.handleBindApplication(Native Method)
    at android.app.ActivityThread.access$1500(ActivityThread.java:139)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1260)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5105)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by dreamfony** [comment]
Can confirm.
Is there other options to get same functionality?
